<?php

namespace AppBundle\Repository;

/**
 * Comment_PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment_PlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
