<?php

namespace AppBundle\Repository;

/**
 * Comment_EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment_EventRepository extends \Doctrine\ORM\EntityRepository
{
}
