<?php

namespace AppBundle\Repository;

/**
 * Mark_PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mark_PlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
