<?php

namespace AppBundle\Repository;

/**
 * MarkEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkEventRepository extends \Doctrine\ORM\EntityRepository
{
}
